version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
